instagram_celebrities = [
    {"name": "Cristiano Ronaldo", "followers_millions": 661},
    {"name": "Lionel Messi", "followers_millions": 506},
    {"name": "Selena Gomez", "followers_millions": 420},
    {"name": "Dwayne 'The Rock' Johnson", "followers_millions": 394},
    {"name": "Kylie Jenner", "followers_millions": 393},
    {"name": "Ariana Grande", "followers_millions": 375},
    {"name": "Kim Kardashian", "followers_millions": 356},
    {"name": "Beyoncé", "followers_millions": 311},
    {"name": "Khloé Kardashian", "followers_millions": 302},
    {"name": "Justin Bieber", "followers_millions": 294},
    {"name": "Kendall Jenner", "followers_millions": 287},
    {"name": "Taylor Swift", "followers_millions": 281},
    {"name": "Virat Kohli", "followers_millions": 274},
    {"name": "Jennifer Lopez", "followers_millions": 248},
    {"name": "Neymar Jr.", "followers_millions": 231},
    {"name": "Nicki Minaj", "followers_millions": 225},
    {"name": "Miley Cyrus", "followers_millions": 212},
    {"name": "Katy Perry", "followers_millions": 204},
    {"name": "Zendaya", "followers_millions": 178},
    {"name": "Lisa (BLACKPINK)", "followers_millions": 106},
    {"name": "Shakira", "followers_millions": 96},
    {"name": "Ed Sheeran", "followers_millions": 97},
    {"name": "Emma Watson", "followers_millions": 58},
    {"name": "Priyanka Chopra", "followers_millions": 77},
    {"name": "Will Smith", "followers_millions": 62},
    {"name": "Billie Eilish", "followers_millions": 91},
    {"name": "Chris Hemsworth", "followers_millions": 54},
    {"name": "Gal Gadot", "followers_millions": 53},
    {"name": "Ryan Reynolds", "followers_millions": 44},
    {"name": "Tom Holland", "followers_millions": 53},
    {"name": "Cardi B", "followers_millions": 113},
    {"name": "Harry Styles", "followers_millions": 80},
    {"name": "BTS", "followers_millions": 103},
    {"name": "Bruno Mars", "followers_millions": 70},
    {"name": "LeBron James", "followers_millions": 110},
    {"name": "Rihanna", "followers_millions": 117},
    {"name": "David Beckham", "followers_millions": 73},
    {"name": "Sophie Turner", "followers_millions": 32},
    {"name": "The Weeknd", "followers_millions": 78},
    {"name": "Kourtney Kardashian", "followers_millions": 131},
    {"name": "Jared Leto", "followers_millions": 45},
    {"name": "Benedict Cumberbatch", "followers_millions": 40},
    {"name": "Camila Cabello", "followers_millions": 74},
    {"name": "Kris Jenner", "followers_millions": 80},
    {"name": "Zayn Malik", "followers_millions": 50},
    {"name": "Gigi Hadid", "followers_millions": 74},
    {"name": "Hailey Bieber", "followers_millions": 54},
    {"name": "V (BTS)", "followers_millions": 63},
    {"name": "Jimin (BTS)", "followers_millions": 61}
]
